#!/bin/bash
# Compares the puppet vim-syntax files, and if they are different, it creates
# a new tarball, uploads it to dev.gentoo.org and updates the ebuild accordingly

OLD=$1
NEW=$2
TMP="/tmp/$0"
DISTFILES="/usr/portage/distfiles"

[[ -d $TMP ]] && rm -rf $TMP
mkdir -p $TMP/{$OLD,$NEW}

for PV in $OLD $NEW; do
    pushd $TMP/$PV > /dev/null
    if [[ $PV == $OLD ]]; then
        # Get the old puppet-syntax tarball and extract it
        [[ -s $DISTFILES/puppet-syntax-$PV.tar.gz ]] || wget http://dev.gentoo.org/~tampakrap/tarballs/puppet-syntax-$PV.tar.gz -P $DISTFILES
        tar xvzf $DISTFILES/puppet-syntax-$PV.tar.gz
    else
        # Get the puppet tarball and extract it
        [[ -s $DISTFILES/puppet-$PV.tar.gz ]] || wget http://www.puppetlabs.com/downloads/puppet/puppet-$PV.tar.gz -P $DISTFILES
        tar xvzf $DISTFILES/puppet-$PV.tar.gz
        # Compare the files
        for plugindir in indent syntax ftdetect ftplugin; do
            diff -ru puppet-$PV/ext/vim/$plugindir/puppet.vim $TMP/$OLD/puppet-syntax-$OLD/$plugindir/puppet.vim >> $TMP/diffs
        done
        if [[ -s $TMP/diffs ]]; then
            # Files have changed, create and upload new tarball
            cp -r puppet-$PV/ext/vim puppet-syntax-$PV
            tar cvzf puppet-syntax-$PV.tar.bz2 puppet-syntax-$PV
            scp puppet-syntax-$PV.tar.bz2 woodpecker:~/public_html/tarballs
        else
            echo "The files haven't changed, exiting"
            exit
        fi
    fi
    popd > /dev/null
done

pushd ~/Source_Code/gentoo/gentoo-x86/app-vim/puppet-syntax > /dev/null
cp puppet-syntax-$OLD.ebuild puppet-syntax-$NEW.ebuild
cvs add puppet-syntax-$NEW.ebuild
repoman manifest
repoman full -d
popd > /dev/null
