#!/bin/bash
# Compares the puppet vim-syntax files.
# 1) If they are different, this script creates a new tarball, uploads it
# to dev.gentoo.org and updates the ebuild accordingly
# 2) If they are not different, it just renames the snapshot and the ebuild

OLD=$1
NEW=$2
TMP="/tmp/$0"
DISTFILES=/usr/portage/distfiles

[[ -d $TMP ]] && rm -rf $TMP
mkdir -p $TMP/{$OLD,$NEW}

for PV in $OLD $NEW; do
    pushd $TMP/$PV > /dev/null
    # Get the puppet tarball and extract it
    [[ -s $DISTFILES/puppet-$PV.tar.gz ]] || wget http://www.puppetlabs.com/downloads/puppet/puppet-$PV.tar.gz -P $DISTFILES
    tar xvzf $DISTFILES/puppet-$PV.tar.gz
    if [[ $PV == $OLD ]]; then
        # Get the old puppet-syntax tarball and extract it
        [[ -s $DISTFILES/puppet-syntax-$PV.tar.gz ]] || wget http://dev.gentoo.org/~tampakrap/tarballs/puppet-syntax-$PV.tar.gz -P $DISTFILES
        tar xvzf /usr/portage/distfiles/puppet-syntax-$PV.tar.gz
    else
        cp -r puppet-$PV/ext/vim puppet-syntax-$PV
        tar cvzf puppet-syntax-$PV.tar.bz2 puppet-syntax-$PV
        scp puppet-syntax-$PV.tar.bz2 woodpecker:~/public_html/tarballs
    fi
    popd > /dev/null
done

pushd ~/Source_Code/gentoo/gentoo-x86/app-vim/puppet-syntax > /dev/null
cp puppet-syntax-$OLD.ebuild puppet-syntax-$NEW.ebuild
cvs add puppet-syntax-$NEW.ebuild
repoman manifest
repoman full -d
popd > /dev/null
