#!/bin/bash
# This script creates symlinks of the various personal scripts I keep in my tampakrap/scripts.git repository

. /etc/init.d/functions.sh

if [[ $(whoami) != "root" ]]; then
	eerror "Must be run as root, terminating"
	exit 1
fi

USER="tampakrap"

function _update() {
	local DESTINATIONS="/usr/local/sbin /usr/local/bin"

	einfo "Update symlinks for ${HOSTNAME}"

	# Desktop/Laptop OR Server
	if [[ ${HOMEDIR} == 1 ]]; then
		REPOSITORY="/home/$USER/Source_Code/raekwon/scripts"
		[[ -L /home/$USER/.gitconfig ]] || \
			( su -c "ln -s ${REPOSITORY}/gitconfig ~/.gitconfig" $USER && einfo "Installed .gitconfig" )
		[[ -L /home/$USER/.ssh/config ]] || \
			( su -c "ln -s ${REPOSITORY}/sshconfig ~/.ssh/config" $USER && einfo "Installed .ssh/config" )
	else
		REPOSITORY="/var/repos/scripts"
		pushd $REPOSITORY > /dev/null 2>&1
		git pull > /dev/null
		popd > /dev/null 2>&1
	fi

	# Include scripts from work repository
	[[ -n ${WORK} ]] && WORK_REPOSITORY="/home/$USER/Source_Code/suse/$USER/scripts"

	# Install the scripts
	for DESTINATION in ${DESTINATIONS}; do
		if [[ ${DESTINATION} == "/usr/local/sbin" ]]; then
			SCRIPTS=${SBIN}
		else
			SCRIPTS=${BIN}
		fi
		for script in ${SCRIPTS}; do
			if [[ -f ${REPOSITORY}/${script} ]]; then
				[[ -L ${DESTINATION}/${script} ]] || \
				( ln -s ${REPOSITORY}/${script} ${DESTINATION} && 
				ewarn "New script ${script} installed in ${DESTINATION}" )
			elif [[ -n ${WORK} ]] && [[ -f ${WORK_REPOSITORY}/${script} ]]; then
				[[ -L ${DESTINATION}/${script} ]] || \
				( ln -s ${WORK_REPOSITORY}/${script} ${DESTINATION} &&
				ewarn "New script ${script} installed in ${DESTINATION}" )
			fi
		done
		# Install additional work scripts that don't reside in WORK_REPOSITORY
		[[ -n ${WORK} ]] && ${WORK_REPOSITORY}/create_work_symlinks
	done

	# /etc/hosts.d
	[[ -L /etc/hosts.d ]] || ( ln -s ${REPOSITORY}/hosts.d /etc && ewarn "Installed hosts.d" )

	einfo "Done"
}

case $HOSTNAME in
	canibus)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update"
		BIN="create_repolinks git packagelist ssh wakeonlan"
		HOMEDIR=1
		;;

	virtuoso)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update"
		BIN="create_repolinks music-sync git packagelist ssh wakeonlan"
		HOMEDIR=1
		WORK=1
		;;

	madlib)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update"
		BIN="wakeonlan"
		;;

	eyedea)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update-notifier"
		BIN="wakeonlan"
		;;

	evidence)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update-notifier"
		BIN="wakeonlan"
		;;

	everlast)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update-notifier"
		BIN="wakeonlan"
		;;

	raekwon)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update-notifier"
		BIN="wakeonlan"
		;;

	xzibit)
		SBIN="cleanup create_symlinks emerge-tmpfs host-update update"
		BIN="create_repolinks get-swamp-id git packagelist ssh wakeonlan"
		HOMEDIR=1
		WORK=1
		;;

	*)
		eerror "${HOSTNAME} not found, terminating"
		exit 1
esac

_update
