#!/usr/bin/env bash

help() {
    cat << EOF
Prints the vault github token via different methods.

Valid argument: "dotfile" (default), "pass", "op".
EOF
}

OPTION=$1
[[ -z $OPTION ]] && OPTION="dotfile"

case "$OPTION" in
    dotfile) VAULT_GITHUB_API_TOKEN=$(cat ${HOME}/.config/vault-tec) ;;
    pass) VAULT_GITHUB_API_TOKEN=$(pass jobandtalent/github-token-jt-vault) ;;
    op)
        OP_SESSION=$(1pass_signin)
        VAULT_GITHUB_API_TOKEN=$(op --session $OP_SESSION --vault Jobandtalent get item "GitHub token jt-vault" --fields password)
        ;;
    *) help && exit 1 ;;
esac

echo $VAULT_GITHUB_API_TOKEN
