#!/bin/bash
# git wrapper in order to clone specific repositories as regular user
# (instead of portage) adn preserve permissions in updates
# In order to perform corectly it needs the following in /etc/sudoers:
# portage ALL=($USER) NOPASSWD: /usr/bin/git *
# ... and the following in /etc/make.conf:
# KDE_DEVELOPER=1
# and a ~/.gitconfig similar to the one included in this repository

source /etc/make.conf

USER="tampakrap"
GIT="/usr/bin/git"

if [[ $1 == 'clone' ]]; then
	if [[ $2 == "git://anongit.kde.org/"* ]] && [[ $KDE_DEVELOPER == 1 ]]; then
		KDE_REPO=$(echo $2 | sed 's:git\://anongit.kde.org/::')
		sudo -u $USER $GIT $1 kde:$KDE_REPO
#	for some stupid reason the following throws perm error, that the dir can't be created
#	elif [[ $2 == "git://git.overlays.gentoo.org/"* ]] && [[ $GENTOO_DEVELOPER == 1 ]];then
#		GENTOO_REPO=$(echo $2 | sed 's:git\://git.overlays.gentoo.org/::')
#		sudo -u $USER $GIT $1 gentoo:$GENTOO_REPO
	else
		$GIT $@
	fi
else
	if [[ ! -w .git/config ]] && [[ ${PWD%/*} == $DISTDIR/egit-src ]]; then
		sudo -u $USER $GIT $@
	else
		$GIT $@
	fi
fi
