#!/usr/bin/env python
# Updates the info of the gentoo servers. Also it merges files under /etc/hosts.d in /etc/hosts

### TODO ###
# Check if /etc/hosts.d symlink exists first
######

try:
	from BeautifulSoup import BeautifulSoup
except ImportError:
	print "Please emerge -av dev-python/beautifulsoup"
	exit()
from StringIO import StringIO
try:
	import pycurl
except ImportError:
	print "Please emerge -av dev-python/pycurl"
	exit()
import shutil
import socket
import sys

serverlist = []
hostsmodules = ['main', 'home-gr', 'home-cz', 'gentoo-el', 'suse', 'linuxteam', 'kde', 'gentoo']

def fetch_gentoo_serverlist():
	# Fetches the Gentoo servers' names and puts them in the serverlist array
	global serverlist
	b = StringIO()
	conn = pycurl.Curl()
	conn.setopt(pycurl.URL, 'http://www.gentoo.org/proj/en/infrastructure/server-specs.xml?passthru=1')
	conn.setopt(pycurl.WRITEFUNCTION, b.write)
	conn.perform()
	soup = BeautifulSoup(b.getvalue())
	ti = soup.findAll('ti')
	i = 0
	while i < len(ti):
		if ti[i].contents[0][-1] == '*':
			hostname = ti[i].contents[0][:-1]
		else:
			hostname = ti[i].contents[0]
		i = i + 9
		serverlist.append(hostname)

def update_hosts_module(infra):
	# Gets the server's IP, and writes name and IP in /etc/hosts.d/$infra
	global serverlist
	f = open('/etc/hosts.d/%s' % infra, 'w')
	for server in serverlist:
		ip = socket.gethostbyname_ex('%s.gentoo.org' % server)[2][0]
		if len(ip) <= 11:
			ip = ip + '\t'
		f.write('%s\t%s\n' % (ip, server))
	f.close()

def merge_hosts_modules():
	# Merges the files from /etc/hosts.d/* to /etc/hosts
	f = open('/etc/hosts', 'w')
	for hostfile in hostsmodules:
		f.write('\n# %s\n' % hostfile)
		shutil.copyfileobj(open('/etc/hosts.d/%s' % hostfile, 'r'), f)
	f.close()

def main():
	try:
		if sys.argv[1] == 'gentoo':
			fetch_gentoo_serverlist()
			update_hosts_module(sys.argv[1])
	except IndexError:
		pass
	merge_hosts_modules()

if __name__ == '__main__':
	main()
