#!/bin/bash
USER="tampakrap"
LDAP_USER="tchatzimichos"
DAY=$(date +%A)
HOUR=$(date +%H)
if [[ $DAY != "Saturday" ]] && [[ $DAY != "Sunday" ]]; then
    if [[ $HOUR < "10" ]] || [[ $HOUR > "19" ]]; then
        for account in $USER $LDAP_USER; do
            su -c "keychain --clear" $account > /dev/null 2>&1
        done
    fi
else
    for account in $USER $LDAP_USER; do
        su -c "keychain --clear" $account > /dev/null 2>&1
    done
fi
