#!/bin/sh

DAY=`date +%A`
HOUR=`date +%H`

case $DAY in
    Saturday|Sunday) $COMMAND ;;
    *) if [ "$HOUR" -lt 9 ] || [ "$HOUR" -gt 19 ]; then
           keychain -q --clear
           echo RELOADAGENT | gpg-connect-agent > /dev/null
       fi ;;
esac
