#!/bin/bash

# Prints the mailboxes in a mutt friendly format, so that they are properly
# displayed at the sidebar

for dir in $(ls ~/.Mail/$1 | sed -e 's/ /##/' | LC_ALL=C sort); do
    VAR+="=$1/${dir/\#\#/\\ } "
done

echo $VAR
