#!/bin/bash

DEFAULT_SITEPP="/etc/puppet/manifests/site.pp"
DEFAULT_MODULEPATH="/etc/puppet/modules"

help() {
    echo
    echo "Bootstrapping puppetmaster script"
    echo
    echo "Options:"
    echo "-s <path> Path of manifests/site.pp. Default is ${DEFAULT_SITEPP}."
    echo "-m <path> Modulepath. Default is ${DEFAULT_MODULEPATH}. If they are more than one, use quotes and separate them with ':'."
    echo "-r <path> Path of the puppet repository."
    echo "-l <url>  Git URL of the repository"
    echo "-t        Clone the puppet repository to /tmp, and then copy to final destination."
    echo "-u        Update the repository."
    echo "-d        Delete configs/packages before bootstrapping."
    echo "-6        Master is IPv6 only."
    echo
    exit 1
}

if [[ $1 == "--help" ]]; then
    help
fi

SITEPP=${DEFAULT_SITEPP}
MODULEPATH=${DEFAULT_MODULEPATH}
REPOSITORY=
LINK=
UPDATE=
TEMPREPOSITORY=
DELETE=
IPV6=

while getopts s:m:r:l:tud6h arg; do
    case ${arg} in
        s) SITEPP=${OPTARG} ;;
        m) MODULEPATH=${OPTARG} ;;
        r) REPOSITORY=${OPTARG} ;;
        l) LINK=${OPTARG} ;;
        t) TEMPREPOSITORY=1 ;;
        u) UPDATE=1 ;;
        d) DELETE=1 ;;
        6) IPV6=1 ;;
        h) help ;;
        *) help ;;
        ?) help ;;
    esac
done

if [[ -z ${REPOSITORY} ]] || [[ -z ${LINK} ]]; then
    help
fi

if [[ -n ${IPV6} ]] && [[ ${LINK} == *github.com* ]]; then
    GITHUB_IPV6="github.iserv.nl"
    LINK=${LINK/github.com/${GITHUB_IPV6}}
fi

if [[ -n ${TEMPREPOSITORY} ]]; then
    CLONE_REPOSITORY_PATH="/tmp/puppet_tmp"
else
    CLONE_REPOSITORY_PATH=${REPOSITORY}
fi

if [[ -n ${DELETE} ]]; then
    if [[ -f /etc/gentoo-release ]]; then
        PUPPETMASTER_INIT="puppetmaster"
        rm -rf /etc/portage/package.{keywords,use,make.conf} /var/cache/eix /etc/make.conf
        emerge -C puppet net-tools
        emerge --depclean
    elif [[ -f /etc/SuSE-release ]]; then
        PUPPETMASTER_INIT="puppetmasterd"
        zypper rm -y puppet-server
    fi
    rm -rf /etc/puppet /var/lib/puppet
    [ -f /etc/init.d/${PUPPETMASTER_INIT} ] && /etc/init.d/${PUPPETMASTER_INIT} stop
fi

if [[ -f /etc/gentoo-release ]]; then
    USE="old-output" emerge app-admin/puppet
elif [[ -f /etc/SuSE-release ]]; then
    zypper in -y puppet-server
fi

if [[ -d ${CLONE_REPOSITORY_PATH} ]]; then
    if [[ -n ${UPDATE} ]]; then
        pushd ${CLONE_REPOSITORY_PATH}
        git pull
        popd
    fi
else
    git clone ${LINK} ${CLONE_REPOSITORY_PATH}
    pushd ${CLONE_REPOSITORY_PATH}
    git submodule init
    [[ -n ${IPV6} ]] && find .git -type f -name config -exec sed -i -e "s/github.com/${GITHUB_IPV6}/g" {} \;
    git submodule update
    popd
fi

[[ -n ${TEMPREPOSITORY} ]] && cp -r ${CLONE_REPOSITORY_PATH} ${REPOSITORY}

echo "[main]
  modulepath = ${MODULEPATH}
" > /etc/puppet/puppet.conf

export RUBYLIB=$(find $(echo ${MODULEPATH} | tr ':' ' ') -type d -name lib -print0 | tr '\0' ':')

puppet apply --debug --verbose ${SITEPP}
