#!/usr/bin/env python
# Random password generator
# TODO: arg -l for length
# TODO: arg -a for all chars, else use \w only

from random import choice
from sys import argv
import string

try:
    print ''.join([choice(string.printable[:-6]) for i in range(int(argv[1]))])
except (IndexError, TypeError):
    print 'You need to specify the length of the password as parameter'
    exit(1)
