#!/usr/bin/env python

from sys import argv
import string
from random import choice

try:
    ''.join([choice(string.printable[:-6]) for i in range(argv[1])])
except (IndexError, TypeError):
    print 'You need to specify the length of the password as parameter'
    exit(1)
