#!/bin/bash
# Simple ssh wrapper, in order to easily access:
# 1) my home servers from my laptop when I am away from HOME_GR
# 2) my work pc
# 3) my laptop

SSID_GR="guru"
SSID_CZ="steele"
SSH="/usr/bin/ssh"
ADDR="home.tampakrap.gr -p"
# TODO PARSE THEM FROM ~/.sshconfig
SERVER1_NAME="eyedea"
SERVER1_PORT="2107"
SERVER2_NAME="evidence"
SERVER2_PORT="2108"
SERVER3_NAME="everlast"
SERVER3_PORT="2109"

# Check if the current machine is desktop or laptop, and if it is inside HOME_GR or HOME_CZ
if [[ -a /sbin/iwconfig ]]; then
	CURRENT_SSID=`/sbin/iwconfig wlan0 | grep ESSID | awk -F: '{ print $2 }' | tr -d '"'`
	CURRENT_SSID=${CURRENT_SSID//[[:space:]]}
	if [[ $CURRENT_SSID = $SSID_GR ]]; then HOME_GR=1 fi
	if [[ $CURRENT_SSID = $SSID_CZ ]]; then HOME_CZ=1 fi
else
	CURRENT_IP=`/sbin/ifconfig eth0 | grep 'inet' | awk '{ print $2}' | cut -d. -f1-3`
	if [[ $CURRENT_IP='192.168.2' ]]; then HOME_GR=1 fi
	if [[ $CURRENT_IP='192.168.11']]; then HOME_CZ=1 fi
fi

# Connect to HOME_GR servers
if [[ $1 == $SERVER1_NAME ]] || [[ $1 == $SERVER2_NAME ]] || [[ $1 == $SERVER3_NAME ]]; then
	if [[ -n $HOME_GR ]]; then
		$SSH $@
	else
		case "$1" in
			$SERVER1_NAME) $SSH $ADDR $SERVER1_PORT ;;
			$SERVER2_NAME) $SSH $ADDR $SERVER2_PORT ;;
			$SERVER3_NAME) $SSH $ADDR $SERVER3_PORT ;;
		esac
	fi
# Connect to xzibit
elif [[ $1 == "xzibit" ]]; then
	if grep -q 10.20 /etc/resolv.con; then
		echo "You need to connect to SUSE VPN first"
	else
		$SSH $@
	fi
# Connect to virtuoso
# Based on common sense:
# 1) if I'm at work then virtuoso is at HOME_CZ
# 2) if I'm at HOME_GR, then virtuoso is also there
elif [[ $1 == "virtuoso" ]]; then
	if [[ -n $HOME_GR ]]; then
		$SSH 192.168.2.102
	else
		$SSH 192.168.11.102
	fi
else
	$SSH $@
fi
