#!/bin/sh

help() {
    echo
    echo "TODO"
    echo
}

LOCATION="cz"
SSH=

while getopts l:sh arg; do
    case ${arg} in
        l) LOCATION="${OPTARG}" ;;
        s) SSH=1 ;;
        h) help && exit ;;
        *) help && exit 1 ;;
    esac
done

if nmcli c show --active | grep -q SUSE; then
    LOCATION=$(nmcli -f NAME c show --active | grep SUSE | cut -d'-' -f2)
    ACT="down"
else
    ACT="up"
fi

nmcli c $ACT SUSE-${LOCATION}
[ -n "$SSH" ] && [ "$ACT" == "up" ] && sleep 1 && ssh xzibit.suse.cz
