#!/bin/bash

. /etc/init.d/functions.sh

TMPDIR="/tmp/obs-services"
GENTOO_X86=$1

SERVICES=(
    download_files
)

for service in ${SERVICES[@]}
do
    PN="obs-service-${service}"
    [[ -d ${TMPDIR} ]] && rm -rf ${TMPDIR}
    mkdir ${TMPDIR}
    pushd ${TMPDIR} > /dev/null
    einfo "Getting version for ${service}"
    wget "https://build.opensuse.org/package/view_file?file=${PN}.spec&package=${PN}&project=openSUSE%3ATools" -O ${PN}.spec
    PV=`grep 'Version:' /tmp/obs-services/${PN}.spec | cut -d':' -f2`
    popd > /dev/null

    pushd ${GENTOO_X86}/dev-util/${PN} > /dev/null
    einfo "Getting previous version"
    previous_PV="`ls -1 ${PN}* | sort | tail -n1 | cut -d'.' -f2 | cut -d'-' -f4`"
    einfo "Previous version is ${previous_PV}"
    einfo "Bumping"
    cp ${PN}-${previous_PV}.ebuild ${PN}-${PV}.ebuild
    cvs add ${PN}-${PV}.ebuild
    repoman manifest
    repoman commit -m "Version bump"
    popd > /dev/null
done
