#!/bin/bash
# Updates the system and mails the output to the admin

echo "From: portage@$HOSTNAME.tampakrap.gr" > /tmp/upd.notify
echo "To: tampakrap@gmail.com" >> /tmp/upd.notify
echo "Subject: $HOSTNAME: emerge update, $(date +%Y-%m-%d)" >> /tmp/upd.notify
echo "" >> /tmp/upd.notify
eix-sync > /dev/null 2>&1
emerge -uDNpv @world >> /tmp/upd.notify 2>&1
sendmail -t root < /tmp/upd.notify
rm /tmp/upd.notify > /dev/null 2>&1
