#!/bin/bash
# Library that returns operating system

if [[ -f /etc/gentoo-release ]]; then
    OPERATINGSYSTEM="gentoo"
elif [[ -f /etc/SuSE-release ]]; then
    OPERATINGSYSTEM="suse"
elif [[ -f /etc/debian_version ]]; then
    OPERATINGSYSTEM="debian"
fi
